import React from 'react';
import Header from "../components/Header";

export default function TermsOfService() {
    return (
        <div className="terms-of-service flex flex-col min-h-screen">
            <Header />
            <main className="flex-grow container mx-auto px-4 py-8 pt-32" style={{ backgroundColor: 'white', paddingTop: '124px' }}>
                <div className="flex justify-center mb-6">
                    <h1 className="text-3xl font-bold">Terms and Conditions</h1>
                </div>
                <section className="mb-8">
                    <p className="font-bold mb-4">DO NOT USE THE SITE FOR EMERGENCY MEDICAL NEEDS. IF YOU EXPERIENCE A MEDICAL EMERGENCY CALL 911.</p>
                    <p>These turniphealth.com Terms and Conditions of Use (“Agreement”) govern your use of our Services. You accept this Agreement either by using the Services, by indicating your acceptance on our website, or by executing a Services Agreement. This Agreement is effective as of the date you first access or use the Site or Services (the “Effective Date”). This Agreement applies whether you are a casual visitor to the Site, a physician or medical provider who subscribes to the Services in order to appear on the Site (a “Provider”), or a patient who utilizes the Services (a “Consumer”).
You may not access the Services: (a) if you do not agree to these terms and conditions; (b) if you are our direct competitor; or (c) for purposes of monitoring their availability, performance or functionality. The Site and Services are not intended for children under the age of eighteen (18). IF YOU ARE UNDER EIGHTEEN (18) YEARS OF AGE, YOU MUST NOT USE OR ACCESS THE SITE OR SERVICES AT ANY TIME OR IN ANY MANNER.
The Services and the Site are evolving and are continually under development. If you are dissatisfied with the Services in any way, we ask you to tell us by sending an email to turniphealth@gmail.com. We may make changes to this Agreement from time to time. When these changes are made, we will make a new copy of the Agreement available to you through the Site. You are responsible for ensuring that you periodically visit our Site and this Agreement to check for any changes, and your use of the Services after the date on which the updated Agreement is made available to you through the Site constitutes your acceptance of the updated Agreement. If you disagree with changes to the Services or updates to the Agreement, your exclusive remedy is: (i) if you are a casual visitor, to stop visiting the Site; (ii) if you are a Provider, to provide us notice of your intention not to renew your subscription through the link in your Account; or (iii) if you are a Consumer, to cancel your Account.
1. Definitions.
1.1. “Account” means the particular instance of the Site authorized for use by you and your Users (as applicable) under your specific login.
1.2. “Documentation” means the specifications and materials located at the Site about the Services.
1.3. “Services” means all services you order from us and made available by us via the Site and/or other locations designated by us.
1.4. “Services Agreement” means the subscription services agreement entered into between a Provider and Turnip Health relating to the Provider's offer of services to consumers via the Turnip Health platform.
1.5. “Site” means turniphealth.com.
1.6. “Subscription Period” means the subscription time described in the Provider’s Services Agreement.
1.7. "We," "Us" or "Our" means Turnip Health, Inc.
1.8. "You" or "Your" means yourself individually or the company or other legal entity for which you are accepting this Agreement. As used in this Agreement, “you” or “your” may encompass casual browsers, Providers and Consumers, as applicable.
1.9. “User” means an authorized user of the Services.
1.10. "User Data" means all electronic data or information submitted by you and your Users (as applicable).
2. Disclosures/Healthcare Regulatory Information.
2.1. Information You Share. If you choose to post a review of Turnip Health  on the website, please note that your name and city/state will be published on the Turnip Health site publicly. If you do not wish to have your real name published on the site, you should use a pseudonym for your username rather than your real name (i.e., use “57chevy” instead of “JosephBrown”). WE ARE NOT RESPONSIBLE FOR THE DISCLOSURE OR PUBLICATION OF ANY PRIVATE INFORMATION THAT YOU SHARE PUBLICLY ON THE SITE. We consider health information to be private information, and recommend against disclosing your identity publicly on the Site. See Section 8, together with our Privacy Policy, for more information on our confidentiality obligations.
2.2. No Medical Advice. WE DO NOT PROVIDE MEDICAL ADVICE, NOR DO WE PROVIDE ANY GUIDANCE OR SUGGESTED TREATMENT FOR YOUR PARTICULAR SITUATION OR ANY OTHER FORM OF MEDICAL TREATMENT. We never recommend or endorse any specific tests, physicians, products, procedures, opinions, or other medical information. We have not evaluated the education, training, experience or credentials of any doctors or health care providers, nor have we evaluated the acceptability, health, or suitability of any patient for any particular procedure. Reliance on any information provided by the Site, whether you are a receiver or provider of healthcare services is solely at your own risk. We simply offer a marketplace platform that allows healthcare providers to advertise and provide information about their services to potential patients. You should always seek the advice of a medical professional regarding your health and wellness. We are not responsible for any services provided/not provided by medical professionals who treat you as a result of the Site and Services or your use thereof.
2.3. HIPAA. Turnip Health is not a “covered entity,” “health insurance issuer,” “health care clearinghouse” or “health care provider” and is therefore not required to comply with the privacy rules and security rules implemented under the Health Insurance Portability and Accountability Act of 1996 (HIPAA). You are strongly encouraged to discuss your provider’s health information privacy policies and procedures with your provider.
2.4. Email Communication. By utilizing our services or replying to our emails, you acknowledge that you are aware that email is not a secure method of communication, and that you agree to the risks. If you would prefer not to exchange personal health information via email, please notify us at turniphealth@gmail.com.
3. Services.
3.1. Subscription Services for Providers. Upon a Provider’s payment for Services and execution of a Services Agreement with Turnip Health , we will make the Services available to the Provider through its Account and/or in the manner described in the agreement during the Subscription Period.
3.2. Service Commitment. We will use commercially reasonable efforts to make the Services available 24 hours a day, 7 days a week, except for: (a) planned downtime (generally, but not necessarily, during weekend hours between 6:00 a.m. and 11:00 a.m. Central Time or during low traffic times during the week); (b) emergency maintenance; or (c) any unavailability caused by circumstances beyond our reasonable control, including, without limitation, acts of God, acts of government, floods, fires, earthquakes, civil unrest, acts of terror, strikes or other labor problems, infrastructure or Internet connectivity provider failures or delays, and denial of service or other malicious attacks. We will provide the Services in accordance with applicable laws and government regulations.
3.3. Updates and Outages. It may be necessary, from time to time, for Turnip Health to perform scheduled or unscheduled repairs, maintenance, upgrades, or updates. Updates are designed to improve, enhance and further develop the Services and may take the form of bug fixes, enhanced functionality, or other updates. These activities may temporarily degrade the quality of the Services or result in a partial or complete outage of the Service. Turnip Health  provides no assurance that you will receive advance notification of such activities or that the Services will be uninterrupted or error-free. Any degradation or interruption of the Services will not give rise to any rights against Turnip Health  or any remedies for you. You agree to such activities as part of your use of the Services.
3.4. Your Duties. You agree to provide true, accurate, current and complete information about yourself and your Users as requested by Turnip Health . You also agree to update the information about yourself and your Users promptly, and as necessary, to keep it current and accurate. You may not impersonate, imitate, or pretend to be somebody else when using our Services. You are responsible for safeguarding and maintaining the confidentiality of any passwords or other credentials, and you agree not to disclose such credentials to any third party. You are solely responsible for all activities that occur under your Account, whether or not you have authorized such activities or actions, including, without limitation, Users’ compliance with this Agreement. You are responsible for the accuracy, quality and legality of User Data, and for ensuring that the Services are used only in accordance with the Services Agreement, Documentation, and applicable laws and government regulations. You agree to use commercially reasonable efforts to prevent unauthorized access to or use of the Services and to notify us immediately of any such unauthorized access or use, or if you know or suspect that any unauthorized person is using or has access to your password or your account (for example, your password has been lost or stolen, someone has attempted to use the Services or Sites through your account without your consent or your account has been accessed without your permission). We strongly recommend that you do not use the Services or access the Sites on any public computer.
4. API
We do not currently offer API access to third parties. If you would like API access to Turnip Health 's website in some way, please contact us at turniphealth@gmail.com.
5. Restrictions
5.1. Limitations on Use. You may not use the Services or accept this Agreement if you are not of a legal age to form a binding contract with us. The Site and Services may be used and accessed for lawful purposes only. By accessing or using the Site or Services, you agree to abide by all applicable local, state, national, and foreign laws, treaties, and regulations in connection with your use of the Site and its content, and you agree not to use the Services for any purpose that is prohibited by this Agreement. The Services may be subject to other limitations, as specified in the Services Agreement and/or Documentation.
5.2. Prohibited Activities. You shall not: (a) make the Services available to anyone other than Users; (b) sell, resell, rent or lease the Services; (c) use the Services to store or transmit infringing, libelous, or otherwise unlawful or tortious material, or to store or transmit material in violation of third-party privacy rights; (d) use the Services for any malicious purpose; (e) interfere with or disrupt the integrity or performance of the Services or third-party data contained therein; (f) build a product or service that is competitive to the Services or use the Services in a way that competes with us; or (g) attempt to gain unauthorized access to the Services or their related systems or networks.
5.3. Examples of Prohibited Activities. By way of example, and not as a limitation, you agree that you will not take any of the following actions while using or accessing the Site or Services:
5.3.1. in any manner transmit or submit any content to which you do not have the lawful right to copy, transmit, and display (including any content that would violate any confidentiality or fiduciary obligations that you might have with respect to the content);
5.3.2. in any manner transmit or submit any content that includes anyone's identification documents or sensitive financial information;
5.3.3. in any manner transmit or submit any content that infringes the intellectual property rights or violates the privacy rights of any third party (including, without limitation, copyright, trademark, patent, trade secret, or other intellectual property right, or moral right, or right of publicity);
5.3.4. in any manner transmit or submit content or material that is unlawful, threatening, harmful, hateful, abusive, harassing, defamatory, deceptive, libelous, deceptive, fraudulent, invasive of another's privacy, tortious, obscene, indecent, vulgar, pornographic, offensive, profane, contains or depicts nudity, contains or depicts sexual activity, promotes bigotry, discrimination or violence, or is otherwise inappropriate or objectionable, as determined by us in our sole discretion;
5.3.5. copy, reproduce, republish, upload, post, transmit, or distribute the Services, the Site, or any content thereof;
5.3.6. share or sell information derived from or related to the Services, the Site, or any content thereof;
5.3.7. modify, translate, alter, adapt, decompile, disassemble (except to the extent applicable laws specifically prohibit such restriction), reproduce, distribute, or display, or create derivative works, compilations, or collective works based on the Services, the Site, or any content thereof;
5.3.8. deciphers, decompiles, disassembles, reverse engineers or otherwise attempts to derive any source code or underlying ideas or algorithms of any part of the Services (including, without limitation, any application or widget), except to the limited extent applicable laws specifically prohibit such restriction;
5.3.9. knowingly or negligently permit other individuals or entities to use or copy the Services or “frame” or “mirror” the Services on any other server or wireless or Internet-based device;
5.3.10. circumvent, disable, or otherwise interfere with security-related features on the Site or features that prevent or restrict use or copying of any content;
5.3.11. impose or take any action that may impose (as we determine in our sole discretion) an unreasonable or disproportionately large load on our (or our third party providers') infrastructure;
5.3.12. interfere with or take any action that may interfere with (as we determine in our sole discretion) the proper working of the Services or any activities conducted on the Service;
5.3.13. use the Services to collect or store Personal Information about other users;
5.3.14. knowingly include or use any false or inaccurate information in any information form or communication, or impersonate any person or entity, including our employees or representatives;
5.3.15. in any way transmit any unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, “pyramid schemes,” or any other form of solicitation, as well as viruses or other computer code that may interrupt, destroy, limit the functionality of the Site, or interfere with the access of any other user to the Site;
5.3.16. conduct commercial activities (whether or not for profit) and/or sales, such as contests, sweepstakes, barter, or advertising, without our prior written consent;
5.3.17. attempt to probe, scan, or test the vulnerability of any system or network operated by us, or breach or impair or circumvent any security or authentication measures protecting the Site;
5.3.18. attack the Site via a denial-of-service attack or a distributed denial-of-service attack or otherwise attempt to interfere with the proper working of the Site;
5.3.19. access, copy, store, reproduce, display, transfer, extract, or harvest Site content or Site data through scraping, crawling, spidering, botting, or other similar means, whether manually or through an automated system or software, whether such Site content or Site data is displayed directly from the Site, Services, or through an Approved Developer’s application, service, website, or otherwise directly or indirectly through a third party;
5.3.20. transmit or upload any material to the Site that contains viruses, trojan horses, worms, time bombs, or any other computer codes, files, or programs that are designed or intended to disrupt, disable, damage, limit or interfere with the proper function of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any system, data, password or other information belonging to us or any third party, or are otherwise harmful or deleterious;
5.3.21. attempt to decipher, decompile, disassemble, reverse engineer, or otherwise attempt to discover or determine the source code of any software or any proprietary algorithm used to provide the Site;
5.3.22. encourage, collaborate, or instruct any other person or entity to do any of the foregoing; or
5.3.23. otherwise violate our guidelines and policies, including without limitation, our privacy policy and/or any other policies and rules incorporated herein.
ANY ATTEMPT TO DO ANY OF THE FOREGOING PROHIBITED ACTS OR TO OTHERWISE UNDERMINE THE OPERATION OF THE SERVICES MAY BE A VIOLATION OF CRIMINAL AND CIVIL LAW. SHOULD SUCH AN ATTEMPT BE MADE, WE RESERVE THE RIGHT, IN ADDITION TO OUR OTHER REMEDIES, TO SEEK DAMAGES (INCLUDING WITHOUT LIMITATION ATTORNEYS’ FEES) FROM ANY SUCH INDIVIDUAL OR ENTITY TO THE FULLEST EXTENT PERMITTED BY LAW.
We reserve the right, in our sole discretion, to audit or otherwise monitor any communication transmitted using the Service. We further reserve the right at all times to review, retain, and/or disclose any information as necessary to satisfy any applicable law, regulation, legal process, governmental request, or business assessment. NOTWITHSTANDING THE FOREGOING, WE HEREBY DISCLAIM ANY OBLIGATION TO MONITOR USE OF THIS SERVICES OR TO RETAIN THE CONTENT ON THIS SITE UNLESS OTHERWISE AGREED OR REQUIRED BY LAW.
5.4. Image Restrictions. If the User Data includes an image, our image guidelines shall apply. We have a zero-tolerance policy against child pornography, and will terminate and report to the appropriate authorities any User who publishes or distributes child pornography.
5.5. Services Reimbursed by Federal or State Health Care Programs Not Permitted. This website is only to be used in connection with the purchase or sale of services which are not reimbursed by any state or federal health care program, including Medicare or Medicaid. No services may be offered on this website to beneficiaries of any such federal or state health care program. No services received as a result of the use of this website may be submitted to any federal or state health care program for reimbursement.
6. Third Party Services and User Data You Send to Public Forums.
6.1. Additional Third Party Terms. You may access and subscribe to third-party products or services as add-ons or additional modules to provide specific functionality to the Services, including, without limitation, specialized industry information and other services. All third-party products and services are provided subject to all restrictions required by us at the time of your subscription to such third-party products or services.
6.2. Integration with Third-Party Services. The Services may contain features designed to interoperate with third-party applications (e.g., Google, Facebook or Twitter applications). To use such features, you must have an account with such applications. If the provider of any such third-party application ceases to allow us to integrate on reasonable terms, we may cease providing such Services features without entitling you to any refund, credit, or other compensation.
6.3. Links to Third Party Sites; Third Party Contact Information. The Services may contain links to other websites and services on the Internet, which are not maintained by us. These links and this contact information are for your convenience only. If you use these links or contact information, you will be outside of the Service. When you leave the Service, you do so at your own risk; we are not responsible for the availability, content or services provided by these third parties. In addition, these links and this contact information are not an endorsement or approval of these third parties. The services of these third parties will be provided under terms determined solely between you and them.
6.4. User Data You Submit to Public Forums. The Services may include features that facilitate your use of third-party publicity applications (e.g., Google, Facebook or Twitter) and/or public forums within the Services (“Public Forums”). The Services will tell you when your User Data is being submitted in a manner that will be posted to a Public Forum. When you submit User Data using these features of the Service, we and such Public Forums only grant you the right to use the Services on a through-to-the-audience basis. Neither we nor such Public Forums shall have any liability to you or any third party for such User Data uploaded to, transmitted or publicly performed through the Services and made publicly available through such a Public Forum.
6.5. Rights in Posted Content. By posting any content to any public area of the Site, you grant, and you represent and warrant that you have the right to grant, to us, and our affiliates, licensees and successors, an irrevocable, perpetual, non-exclusive, fully paid, worldwide license to use, copy, perform, display, reproduce, adapt, modify and distribute such information and content and to prepare derivative works of, or incorporate into other works, such information and content, and to grant and authorize sublicenses of the foregoing. You further represent and warrant that public posting and use of your content by us will not infringe or violate the rights of any third party.
7. Fees and Payment.
7.1. Access Charges. You are responsible for all connectivity costs and expenses required to access the Site, including, without limitation, Internet service provider fees.
7.2. Taxes. Unless otherwise stated, our fees do not include any taxes, levies, duties or similar governmental assessments of any nature, including but not limited to value-added, sales, use or withholding taxes, assessable by any local, state, provincial, federal or foreign jurisdiction (collectively, "Taxes"). You are responsible for paying all Taxes associated with your Account. If we are legally obligated to pay or collect your Taxes under this paragraph, the appropriate amount shall be invoiced to and paid by you.
7.3. Credit Card Fees. When booking an appointment, you may be charged credit card fees, which will be presented at time of payment. You understand and agree that you will be responsible for any such fees associated with your purchase.
7.4. Additional Fees. We reserve the right to assess additional fees, including processing fees, from time to time. You understand and agree that you will be responsible for timely payment of any such fees associated with your Account.
8. Exclusive Turnip Health  Discounts
8.1. Exclusive Turnip Health  Discounts. Exclusive Turnip Health  Discounts (“Discount Agreements” or “Agreements” or “Agreement”) are distributed by Turnip Health and are redeemable for services offered by the Provider identified on the Agreement. The Provider is fully and solely responsible for the care and quality of all services it provides to you and for any and all injuries, illnesses, damages, claims, liabilities and costs (“Liabilities”) it may cause you to suffer, directly or indirectly, in full or in part, whether related to the use or redemption of an Agreement or not. You waive and release Turnip Health and its subsidiaries, affiliates, partners, officers, directors, employees, and agents from any Liabilities arising from or related to any act or omission of a Provider in connection with your use of an Agreement or the services a Provider provides in connection with the Agreement.
By purchasing, viewing a mobile version, printing, accepting, using, or attempting to use any Agreement, you agree specifically to the terms on the Agreement and any additional deal-specific terms advertised in connection with and on the Agreement at the time of purchase and these Terms of Service. These rules apply to all Agreements that we make available, unless otherwise disclosed in connection with the purchase of a particular Agreement, and except as otherwise required by law. In the event of a conflict between these rules and the terms advertised in connection with and on the Agreement at the time of purchase, the terms advertised in connection with and on the Agreement at the time of purchase will control. Any attempt to redeem an Agreement in violation of these Terms of Service will render the Agreement void.
Agreements are not redeemable for cash, unless required by law. Unauthorized or unlawful reproduction, resale, modification, or trade of Agreements is prohibited. Pricing relating to certain Provider Offerings on the Site may change at any time at Turnip Health s discretion, without notice.
Agreements can be paid for at two distinct times: (i) at the time of booking the appointment and (ii) after receiving medical treatment.
8.2. Agreements Paid for at Time of Booking. When an Agreement is paid at the time of booking the appointment, an Agreement has two separate values: (i) the amount paid and (ii) the promotional value. The promotional value is the additional value beyond the amount paid. For example, if you pay $20 for an Agreement that entitles you to $50 of services, the amount paid is $20 (this amount does not expire until it is used) and the promotional value is $30 (this amount expires on the date stated on the Agreement unless expiration of the promotional value is prohibited by law). The Company is responsible for permitting you to redeem the Agreement for at least the amount paid, even after the promotional value has expired. The promotional value of an Agreement may not be combined with other offers and no portion of its value is intended to cover tax or gratuity. Agreements are not reloadable, meaning that the amount paid of the Agreement cannot be increased. Agreements are not transferable.
8.3. Agreements Paid for After Receiving Medical Care. When a customer chooses to pay for the Agreement after receiving medical care, an Agreement has one value: (i) the promotional value. After receiving medical treatment, the Customer presents proof of the Agreement to the Provider, and the Customer’s credit card is charged the total cost of care discounted by the promotional value. The amount of care is paid to the Company, and the Company transfers this amount to the Provider.
The promotional value expires on the date stated on the Agreement unless expiration of the promotional value is prohibited by law. The promotional value of a traditional Agreement may not be combined with other offers and no portion of its value is intended to cover tax or gratuity. Agreements are not transferable.
8.4. Trade-In Program. Agreements paid in full at the time of booking the appointment that are not used for the original appointment can be used to pay for treatments or services at other Providers that accept Exclusive Turnip Health  Discounts. An unused Agreement can be used as a credit equal to the amount paid for the Agreement or another amount specified by Turnip Health . The promotional value offered at one Provider is never redeemable for services from another Provider. You must have an account to participate.
For an Agreement to be eligible for Trade-In
●      Turnip Health , in its sole discretion, must designate the Agreement as eligible.
●      The code on the Agreement must have not been viewed or the Agreement must have not been redeemed.
8.5. Refunds. The Company will not refund any Agreement and all sales are final, unless otherwise stated in the Fine Print.
9. Intellectual Property Rights and Ownership.
9.1. Rights in Services. The Site, Services, and all text, images, designs, graphics, content, source code, object code, data, features, and functionality (including but not limited to all information, software, displays, enablement of video and audio, and the design, selection, and arrangement thereof) are owned by us, our licensors, or other providers of such materials. For purposes of clarity, Turnip Health  owns the right to the compilation, arrangement, and assembly, along with any modifications, variations, updates, versions, and changes to all information entered and stored within our Site database(s) as part of the Site. This material, collectively, is protected by United States copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws. All of the Site content is copyrighted material and is protected by the Copyright Act of 1976. You are not permitted to republish, reproduce, transmit, transfer, prepare derivative versions or works, or otherwise use any content on this Site without our prior, express, and written permission. We reserve all rights, title and interest in and to the Site and the Services, including all related intellectual property rights.
No rights are granted to you hereunder other than as expressly set forth herein, and you do not and will not acquire any intellectual property rights in the Site or Services by your use of the same. Subject to your compliance with this Agreement, together with any Service Agreement, Documentation, or other terms to which you are bound, we grant you a limited, non-exclusive, non-transferable, and revocable license, without the right to sublicense, to access and use the Site and Services. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by us or our licensors, except for the limited license expressly granted herein.
9.2. Suggestions. All feedback, suggestions, enhancement requests, recommendations, ideas, and other submissions disclosed, submitted, or offered to Turnip Health  or otherwise disclosed, submitted, or offered concerning the Services (collectively, “Feedback”) will be Turnip Health ’s property. Such disclosure, submission, or offer of any Feedback by you, including Users, will constitute an assignment to Turnip Health of all worldwide rights, titles, and interests in all copyrights and intellectual property in the Feedback. Turnip Health  is under no obligation to (a) maintain any Feedback in confidence; (b) pay any compensation for any Feedback; or (c) respond to any Feedback.
9.3. Government Use. The Services include "commercial computer software" and related documentation within the meaning of Federal Acquisition Regulation 2.101, 12.212, and 27.405-3 and Defense Federal Acquisition Regulation Supplement 227.7202 and 52.227-7014(a). The Services are highly proprietary to us and our licensors. You shall ensure that all Users, including those that are representatives of the U.S. Government or any other government body, are permitted to use the Services only as expressly authorized under this Agreement. Neither you nor any government body shall receive any ownership, license, or other rights other than those expressly set forth herein, irrespective of: (a) whether you are an agency, agent, or other instrumentality of the U.S. Government or any other government body, (b) whether you are entering into or performing under this Agreement in support of a U.S. Government or any other government agreement or utilizing any U.S. Government or any other government funding of any nature, or (c) anything else.
10. Confidentiality.
10.1. Definition. The term “Confidential Information” means the provisions of a Services Agreement, and any and all information, written or oral, provided or made available by or on behalf of one party or its affiliates, contractors, or vendors to the other party or its affiliates, contractors, or vendors in connection with this Agreement or the parties’ relationship hereunder, whether or not designated as confidential. Information of a third party to whom a party owes a duty of confidentiality will be treated as Confidential Information of that party if it meets the description above. However, Confidential Information does not include information that: (a) was or is publicly available other than as a result of breach of this Agreement by Recipient (as defined below); (b) was or is lawfully received by the Recipient free of any obligation of confidentiality; or (c) is independently developed by or on behalf of the Recipient without use of the Discloser’s Confidential Information.
10.2. Obligations. Each party (“Recipient”) will not access or use Confidential Information of the other party (“Discloser”) for any purposes other than performance of its obligations or receipt of benefits hereunder and shall maintain such information in the strictest confidence, except for disclosures expressly authorized hereunder. Recipient may disclose the Discloser’s Confidential Information to Recipient’s employees, attorneys, advisors, and contractors who have a legitimate “need to know,” provided that Recipient ensures that all such entities and persons are obligated to and do comply with confidentiality obligations consistent with (and no less restrictive than) this Section 8 (Confidentiality), but in no event may you disclose any of our Confidential Information to any of our competitors (or any of their affiliates) or any employees or contractors of any such competitors. Recipient may additionally disclose the Discloser’s Confidential Information to the extent such disclosure is necessary in connection with the enforcement of this Agreement.
10.3. Compelled Disclosure. The Recipient may disclose Confidential Information of the Discloser if it is compelled by law to do so, provided the Recipient gives the Discloser prior notice of such compelled disclosure (to the extent legally permitted) and reasonable assistance, at the Discloser’s cost, if the Discloser wishes to contest the disclosure. If the Recipient is compelled by law to disclose the Discloser’s Confidential Information as part of a civil proceeding to which the Discloser is a party, and the Discloser is not contesting the disclosure, the Discloser will reimburse the Recipient for its reasonable costs of compiling and providing secure access to such Confidential Information.
10.4. Privacy and User Information. For information about our data protection practices, please read our privacy policy, located at https/Turnip Health .com/privacy. This policy explains how we treat User Data and protect your privacy when you use the Services. By accessing or using the Site or Services, and/or by providing any User Data to us, you agree to the use of User Data in accordance with our privacy policy.
10.5. User Data. As described more fully in our privacy policy, you grant us broad rights to use and exploit de-identified data, including de-identified User Data collected by us through your use of the Services, which rights continue even after this Agreement ends. Except for our limited rights to use the User Data set forth throughout this Section 8 and in our privacy policy, we acquire no right, title or interest from you or your Users under this Agreement in or to User Data, including any intellectual property rights therein.
11. Warranties.
11.1. Your Warranties. You warrant that: (a) you have validly entered into this Agreement and have the legal power to do so; (b) you will abide by the restrictions on use of the Services contained herein; and (c) all information or User Data that you provide is truthful, accurate, not misleading, offered in good faith, and that you and your Users have all rights, licenses, permissions and authorizations necessary to upload and transmit such User Data to us. Furthermore, if you are acting on behalf of a company or other legal entity, you represent and warrant that you have the authority to bind that entity to this Agreement.
11.2. DISCLAIMER. NOTWITHSTANDING ANYTHING TO THE CONTRARY, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALL SERVICES, INFORMATION AND MATERIALS ARE PROVIDED “AS IS”, AND WE EXPRESSLY DISCLAIM ANY AND ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION: (A) ANY AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE (WHETHER OR NOT WE KNOW, HAVE REASON TO KNOW, OR HAVE BEEN ADVISED OF ANY SUCH PURPOSE); (B) ANY WARRANTY REGARDING RESULTS OBTAINABLE OR TO BE OBTAINED BY USERS AS A RESULT OF PROVISION OR USE OF THE SERVICES AND MATERIALS PROVIDED HEREUNDER; AND (C) ANY WARRANTY OF UNINTERRUPTED, TIMELY, OR ERROR-FREE OPERATION OF ANY SERVICES. NO ADVICE OR INFORMATION, WHETHER WRITTEN, ORAL OR MULTIMEDIA, OBTAINED BY YOU FROM THE SERVICES SHALL CREATE ANY ADDITIONAL WARRANTY NOT EXPRESSLY STATED IN THIS AGREEMENT. Turnip Health  DOES NOT ENDORSE ANY PROVIDER. FURTHER, Turnip Health  DISCLAIMS ALL WARRANTIES AND LIABILITIES RELATED TO THE PROVIDERS, ANY ACTS OR OMISSIONS THEREOF, AND ANY CONTENT OR SERVICES MADE AVAILABLE THEREBY, WHETHER THROUGH THE SITE OR OTHERWISE. IT IS YOUR RESPONSIBILITY TO EVALUATE THE APPROPRIATENESS, ACCURACY, COMPLETENESS, AND RELIABILITY OF ANY INFORMATION, OPINIONS, ADVICE, OR OTHER CONTENT MADE AVAILABLE BY THE PROVIDERS, WHETHER THROUGH THE SITE OR OTHERWISE, AND Turnip Health HEREBY DISCLAIMS ANY WARRANTIES AND LIABILITIES RELATED TO SUCH CONTENT.
11.3. RISK OF INACCURACY OF INFORMATION. YOU ACKNOWLEDGE THAT MANY FEATURES PROVIDED BY THE SITE ARE INTENDED TO AGGREGATE AND MANAGE THIRD PARTY DATA AND INFORMATION FROM NUMEROUS SOURCES. WE ARE NOT RESPONSIBLE FOR THE ACCURACY, INTEGRITY, QUALITY, LEGALITY, USEFULNESS, OR SAFETY OF SUCH INFORMATION. YOU WAIVE ANY CLAIMS YOU MAY OTHERWISE HAVE, AND YOU AGREE THAT WE WILL NOT BE LIABLE FOR ANY DAMAGES OR INCONVENIENCES YOU MAY SUFFER AS A RESULT OF INACCURATE OR INCOMPLETE DATA OR INFORMATION PROVIDED TO YOU OR YOUR USERS BY THE SERVICE.
11.4. Beta Services. From time to time we may invite you to try, at no charge, our products or services that are not generally available to our customers ("Beta Services"). You may accept or decline any such trial in your sole discretion. Any Beta Services will be clearly designated as Beta, pilot, limited release, developer preview, non-production, or by a description of similar import. Beta Services are provided for evaluation purposes and not for production use, are not supported under our support plan, may contain bugs or errors, and may be subject to additional terms. BETA SERVICES ARE NOT CONSIDERED "SERVICES" HEREUNDER AND ARE PROVIDED "AS IS" WITH NO EXPRESS OR IMPLIED WARRANTY. We may discontinue Beta Services at any time in our sole discretion.
12. Indemnification.
12.1. Indemnification. You shall indemnify, defend, and hold harmless Turnip Health , our licensors and affiliates, and our and their respective directors, officers, employees, contractors, agents, and representatives, from and against any and all claims, demands, suits, causes of action, proceedings, liabilities, losses, costs, or expenses (including, but not limited to, reasonable attorneys’ and expert fees and costs of investigation): (a) arising out of, in connection with, or resulting from your access to or use of the Site or Services, your violation of any provision of this Agreement, or any activity related to your accessing the Site or Services, including without limitation, negligent or wrongful conduct; (b) arising out of the receipt or provision of professional or medical services offered, sold, purchased, or arranged via the Turnip Health platform; (c) alleging that User Data or your use of the Services infringes or misappropriates the intellectual property rights of a third party; (d) alleging that User Data or your use of the Services violates applicable law; (e) arising from any data or security breach caused by you; and/or (f) related to a dispute between you and such third party (whether you are a provider or a patient) (an "Indemnified Claim"), and you shall indemnify us for any damages, attorney fees and costs as a result of, or for any amounts paid by us in respect of an Indemnified Claim. We reserve the right, at your expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will cooperate with us in asserting any available defenses.
12.2. Scope of Indemnification. For purposes of clarity, these indemnification obligations apply to your use of the Site, along with your use of the Site’s content and Services, other than as expressly authorized in this Terms, and your use of any information obtained from the Site or any information you provide to the Site.
13. Limitation of Liability.
13.1. LIMITATIONS. NOTWITHSTANDING ANYTHING TO THE CONTRARY, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NEITHER WE NOR OUR LICENSORS SHALL BE LIABLE WITH RESPECT TO ANY SERVICES AND/OR UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER LEGAL OR EQUITABLE THEORY FOR: ANY AMOUNTS IN EXCESS OF THE APPLICABLE FEES PAID DURING THE THREE (3) MONTH PERIOD IMMEDIATELY PRECEDING THE FIRST EVENT, ACTION, OR OMISSION GIVING RISE TO THE CLAIM FOR WHICH ANY CREDITS OR DAMAGES ARE PAID OR HELD RECOVERABLE HEREUNDER. FOR CLARIFICATION, ANY SERVICE CREDITS PAID BY US SHALL REDUCE OUR LIABILITY CAP ON A DOLLAR-FOR-DOLLAR BASIS AND SHALL NOT BE DEEMED OR TREATED AS AN ADMISSION OF LIABILITY. ALL OF THE FOREGOING LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. YOU MAY ONLY BRING A CLAIM AGAINST US WITHIN SIX (6) MONTHS FROM THE DATE THE PARTICULAR CLAIM ACCRUED OR THE APPLICABLE CAUSE OF ACTION IS PERMANENTLY BARRED. If you are a resident of California, you specifically waive California Civil Code §1542, which states, “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor.”
13.2. EXCLUSION OF CONSEQUENTIAL AND RELATED DAMAGES. IN NO EVENT SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY BUSINESS INTERRUPTION, LOST PROFITS OR REVENUES OR FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, COVER OR PUNITIVE DAMAGES HOWEVER CAUSED, WHETHER IN CONTRACT, TORT OR UNDER ANY OTHER THEORY OF LIABILITY, AND WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING DISCLAIMERS SHALL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW. HOWEVER, IN SUCH EVENT, YOU AGREE THAT SUCH LIMITATIONS OF LIABILITY ARE REASONABLE, AND ARE FUNDAMENTAL ELEMENTS FOR THE SCOPE OF THE SERVICES AND THE FEES CHARGED TO YOU. YOU UNDERSTAND AND ACKNOWLEDGE THAT WE WOULD NOT BE ABLE TO OFFER THE SERVICES TO YOU WITHOUT THESE LIMITATIONS.
14. Term and Termination.
14.1. Term. This Agreement commences on the Effective Date and continues until all User subscriptions granted in accordance with this Agreement and/or a Services Agreement have expired or been terminated or, if you do not have a subscription, until you discontinue use of the Site and Services.
14.2. Term of Provider Subscriptions. Provider subscriptions commence on the start date specified in the applicable Services Agreement and continue for the Subscription Period specified therein. User subscriptions shall automatically renew in accordance with the Services Agreement. The pricing during any such renewal term shall be the same as that during the prior term unless otherwise indicated in the Services Agreement.
14.3. Termination. A party may terminate this Agreement for cause: (a) upon thirty (30) days’ written notice to the other party of a material breach if such breach remains uncured at the expiration of such period; or (b) if the other party becomes the subject of a petition in bankruptcy or any other proceeding relating to insolvency, receivership, liquidation or assignment for the benefit of creditors. We may also terminate this Agreement for any reason upon thirty (30) days written notice to you.
14.4. Payment upon Termination. In no event shall any termination relieve you of the obligation to pay any fees payable to us for the period prior to the effective date of termination.
14.5. Surviving Provisions. Section 7 (Fees and Payment), 8 (Ownership), 9 (Confidentiality), 10.3 (Disclaimer), 11 (Indemnification), 12 (Limitation of Liability), 13.4 (Refund or Payment upon Termination), and 15 (Miscellaneous) shall survive any termination or expiration of this Agreement.
15. Copyright and Trademark Policies.
It is our policy to respond to notices of alleged copyright infringement which comply with applicable law, including the Digital Millennium Copyright Act (DMCA), and to terminate the accounts of repeat infringers in accordance with our DMCA Policy. Trademark infringement complaints can be submitted to us at turniphealth@gmail.com. We'd be quite surprised to receive a trademark complaint.
16. Miscellaneous.
16.1. Notices. You agree that we may provide you with notice, including changes to this Agreement, by email, regular mail or postings in your Account.
16.2. Governing Law; Forum. This Agreement shall be governed by and construed in accordance with the laws of the State of New York, disregarding any conflict-of-laws rules which may direct the application of the laws of another jurisdiction. You agree that venue for all actions relating in any manner to this Agreement, shall be in a federal or state court of competent jurisdiction located in New York. Each party to these terms waives any objection based on forum non conveniens and waives any objection to venue of any action instituted to the extent that an action is brought in the courts identified above.
16.3. Export Compliance. The Services, other technology we make available, and derivatives thereof may be subject to export laws and regulations of the United States and other jurisdictions. Each party represents that it is not named on any U.S. government denied-party list. You shall not permit Users to access or use Services in a U.S.-embargoed country (including, without limitation, Cuba, Iran, North Korea, Sudan or Syria) or in violation of any U.S. export law or regulation.
16.4. Relationship of the Parties. The parties are independent contractors. This Agreement does not create a partnership, franchise, joint venture, agency, fiduciary or employment relationship between the parties.
16.5. No Third-Party Beneficiaries. There are no third-party beneficiaries to this Agreement.
16.6. Severability and Waiver. If any provision hereof is declared invalid by a court of competent jurisdiction, such provision shall be ineffective only to the extent of such invalidity so that the remainder of that provision and all remaining provisions will continue in full force and effect. The failure of Turnip Health to enforce any right or provision in the Agreement will not constitute a waiver of such right or provision unless acknowledged and agreed to by Turnip Health in writing. No waiver by us of any term or condition set forth herein shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of us to assert a right or provision shall not constitute a waiver of such right or provision.
16.7. Attorney Fees. You shall pay on demand all of our reasonable attorney fees and other costs incurred by us to enforce any rights under this Agreement, including without limitation, to collect any fees or charges due us under this Agreement following your breach of Sections 6.1 or 6.2 (Payment).
16.8. Assignment. You may not any of your rights or obligations hereunder, whether by operation of law or otherwise, without the prior written consent of Turnip Health  (not to be unreasonably withheld), except in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of your assets not involving a direct competitor of Turnip Health. Any attempted assignment in contravention of this Section shall be null and void. Subject to the foregoing, this Agreement shall bind and inure to the benefit of the parties, their respective successors and permitted assigns.
16.9. Interpretation. No provision shall be construed against a party by reason of the fact that such party or its legal counsel drafted that provision, notwithstanding any rule of law or any legal decision to the contrary. For purposes of interpreting this Agreement: (a) the terms “herein,” “hereof,” “hereto,” “herewith”, “hereunder,” “hereinafter,” and similar terms shall refer to this Agreement as a whole; (b) the terms “includes” and “including” shall mean “include[ing], without limitation”; (c) references to Sections in any particular Attachment shall refer to Sections in that same Attachment, unless otherwise specified therein; and (d) headings contained herein are for convenience of reference only and shall not affect the interpretation of this Agreement. For purposes of this Agreement, whenever the context requires, the singular number will include the plural, and vice versa.
16.10. Entire Agreement. This Agreement, including all exhibits and addenda hereto and all Services Agreements, constitutes the entire agreement between the parties and supersedes all prior and contemporaneous agreements, proposals or representations, written or oral, concerning its subject matter. No modification, amendment, or waiver of any provision of this Agreement shall be effective unless in writing and either signed or accepted electronically by the party against whom the modification, amendment or waiver is to be asserted. However, to the extent of any conflict or inconsistency between the provisions in the body of this Agreement and any exhibit or addendum hereto or any Services Agreement, the terms of such exhibit, addendum or Services Agreement shall prevail. Notwithstanding any language to the contrary therein, no terms or conditions stated in Your Services Agreement shall be incorporated into or form any part of this Agreement, and all such terms or conditions shall be null and void.
LAST UPDATED October 21, 2024
</p>
                </section>
                {/* Add more sections here for the rest of the terms */}
            </main>
        </div>
    )
};
